class Product {
  final List<String> img;
  final bool like,nuovo;
  final double star;
  final String brand,
      year,
      model,
      description,
      type,
      format,
      sizes,
      colors,
      reviers,
      price,
      previousPrice;

  Product({
    required this.brand,
    required this.year,
    required this.model,
    required this.nuovo,
    required this.img,
    required this.reviers,
    required this.description,
    required this.type,
    required this.format,
    required this.sizes,
    required this.colors,
    required this.star,
    required this.price,
    required this.previousPrice,
    required this.like,
  });
}

List<Product> products = [
  Product(
    brand: 'CANNONDALE',
    year: '2019',
    model: 'ADVENTURE NEO 2 EQ',
    nuovo: false,
    img: ['lib/assets/bike.jpg', 'lib/assets/bike.jpg'],
    reviers: '8560',
    star: 4,
    description:
        'Una bici elettrica perfetta per la citta, le piste ciclabili ed i sentieri di campagna.',
    type: 'E-BIKE',
    format: 'CORSA',
    sizes: 'S M L XL',
    colors: "+4",
    price: '€3.299,00',
    previousPrice: '€3.299,00',
    like: false,
  ),
  Product(
    brand: 'CANNONDALE',
    year: '2019',
    model: 'ADVENTURE NEO 2 EQ',
    nuovo: true,
    img: ['lib/assets/bike.jpg', 'lib/assets/bike.jpg'],
    reviers: '100000',
    star: 5,
    description:
        'Una bici elettrica perfetta per la citta, le piste ciclabili ed i sentieri di campagna.',
    type: 'E-BIKE',
    format: 'CORSA',
    sizes: 'S M L XL',
    colors: "+4",
    price: '€3.299,00',
    previousPrice: '€3.299,00',
    like: false,
  ),
  Product(
    brand: 'CANNONDALE',
    year: '2019',
    model: 'ADVENTURE NEO 2 EQ',
    nuovo: false,
    img: ['lib/assets/bike.jpg', 'lib/assets/bike.jpg'],
    reviers: '8560',
    star: 4,
    description:
        'Una bici elettrica perfetta per la citta, le piste ciclabili ed i sentieri di campagna.',
    type: 'E-BIKE',
    format: 'CORSA',
    sizes: 'S M L XL',
    colors: "+4",
    price: '€3.299,00',
    previousPrice: '€3.299,00',
    like: true,
  ),
  Product(
    brand: 'CANNONDALE',
    year: '2019',
    model: 'ADVENTURE NEO 2 EQ',
    nuovo: true,
    img: ['lib/assets/bike.jpg', 'lib/assets/bike.jpg'],
    reviers: '100000',
    star: 5,
    description:
        'Una bici elettrica perfetta per la citta, le piste ciclabili ed i sentieri di campagna.',
    type: 'E-BIKE',
    format: 'CORSA',
    sizes: 'S M L XL',
    colors: "+4",
    price: '€3.299,00',
    previousPrice: '€3.299,00',
    like: true,
  ),
];
